version: 0.0
os: linux
files:
  - source: /results.txt
    destination: /var/www/html/
  - source: /results.xml
    destination: /var/www/html/
  - source: /index.html
    destination: /var/www/html/
  - source: /
    destination: /erm/

hooks:
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
    
