#!/bin/bash
yum install -y httpd

yum install -y python
sudo amazon-linux-extras install python3.8

python --version
python3 --version

curl -O https://bootstrap.pypa.io/get-pip.py
python3 get-pip.py --user
python3 -m pip --version

cd /erm
python3 -m pip install -r reqs.txt
python3 -m pytest --version
