#!/bin/bash
yum install -y httpd

sudo amazon-linux-extras install python3.8
python3 --version

curl -O https://bootstrap.pypa.io/get-pip.py
python3 get-pip.py --user

pwd
/root/.local/bin/pip3 --version
/root/.local/bin/pip3 install -r ../reqs.txt
pytest --version
pytest --junitxml=results.xml
